[versions]
agp = "7.3.1"
androidx_activity_compose = "1.6.1"
androidx_test = "1.4.0"
androidx_arc_test = "2.1.0"
androidx_test_ext = "1.1.3"
appcompat = "1.5.1"
material = "1.8.0-alpha02"
fragment_ktx = "1.4.5"
fragment_navigation_ktx = "2.5.3"
compile_sdk_version = "33"
compose = "1.3.0"
compose_compiler = "1.3.2"
compose-bom = "2022.12.00"
compose_compilerextension = "1.3.2"
compose_constraintlayout = "1.0.1"
compose_paging = "1.0.0-alpha17"
accompanist = "0.27.0"
coil = "2.2.2"
constraint_layout = "2.1.4"
core_ktx = "1.8.0"
detekt = "1.21.0"
dokka = "1.7.20"
espresso_core = "3.4.0"
junit = "4.13.2"
kotlin = "1.7.20"
ktlint = "0.45.2"
ktlint_gradle = "10.2.1"
min_sdk_version = "21"
target_sdk_version = "33"
benmanesversion = "0.43.0"
dagger = "2.44"
coroutines = "1.6.4"
lifecycle = "2.6.0-alpha03"
lifecycle_extensions = "2.2.0"
okhttp = "4.10.0"
retrofit = "2.9.0"
moshi = "1.14.0"
datastore = "1.0.0"
timber = "5.0.1"
location_service = "21.0.0"
maps_ktx = "3.2.1"
room = "2.4.3"
hamcrest = "2.2"
mockk = "1.13.2"
assertj = "3.23.1"
mockito = "4.8.1"
mockito_kotlin = "4.0.0"
turbine = "1.0.2"
faker = "1.0.2"
paging = "1.0.0-alpha17"
lottie = "5.2.0"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
androidx_activity_compose = { module = "androidx.activity:activity-compose", version.ref = "androidx_activity_compose" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx_material = { module = "com.google.android.material:material", version.ref = "material" }
androidx_fragment_ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment_ktx" }
androidx_navigation_fragment_ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "fragment_navigation_ktx"}
androidx_navigation_ui_ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "fragment_navigation_ktx"}
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "core.ktx" }
androidx_test_rules = { module = "androidx.test:rules", version.ref = "androidx.test" }
androidx_test_runner = { module = "androidx.test:runner", version.ref = "androidx.test" }
androidx_test_ext_junit = { module = "androidx.test.ext:junit", version.ref = "androidx.test.ext" }
androidx_test_ext_junit_ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx.test.ext" }
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.5.3"
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

junit_ext = { module = "androidx.test.ext:junit", version.ref = "junit" }
hamcrest = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest" }
assertj_core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockito_core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito_kotlin = { module = "com.nhaarman:mockito-kotlin", version.ref = "mockito.kotlin" }
androidx_arc_testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx.arc.test" }
javafaker = { module = "com.github.javafaker:javafaker", version.ref = "faker" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-animation-animation = { module = "androidx.compose.animation:animation" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended" }
compose-material-material = { module = "androidx.compose.material:material" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-uitextfonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
compose-ui-util = { module = "androidx.compose.ui:ui-util" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }
compose-paging = { module = "androidx.paging:paging-compose", version.ref = "paging" }
compose_constraint_layout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "compose_constraintlayout" }

accompanist_insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist_permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompanist" }
accompanist-navigation-material = { module = "com.google.accompanist:accompanist-navigation-material", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicator = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-insetsui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
#accompanist_coil = { module = "com.google.accompanist:accompanist-coil", version.ref = "accompanist" }

detekt_formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
espresso_core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso.core" }

coil-coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }

hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
hilt-work = "androidx.hilt:hilt-work:1.0.0"
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger-dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }

coroutines_core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines"}
coroutines_android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines"}
coroutines_test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines"}
coroutines_services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines"}
lifecycle_compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycle"}
lifecycle_livedata_ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle"}
lifecycle_viewmodel_ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle"}
lifecycle_runtime_ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle"}
lifecycle_extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle_extensions"}

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
okhttp_interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp"}
okhttp_mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp"}
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit"}
retrofit_converter_moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit"}
moshi = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi"}
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore"}
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber"}
play_services_location = { module = "com.google.android.gms:play-services-location", version.ref = "location_service"}
maps_utils_ktx = { module = "com.google.maps.android:maps-utils-ktx", version.ref = "maps_ktx"}
maps_ktx = { module = "com.google.maps.android:maps-ktx", version.ref = "maps_ktx"}
room_compiler = { module = "androidx.room:room-compiler", version.ref = "room"}
room_ktx = { module = "androidx.room:room-ktx", version.ref = "room"}
room_runtime = { module = "androidx.room:room-runtime", version.ref = "room"}
room_testing = { module = "androidx.room:room-testing", version.ref = "room"}
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

dokka_gradle_plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka"}
dokka_core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "dokka"}
android_gradle_plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin_gradle_plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint.gradle" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
versions = { id = "com.github.ben-manes.versions", version.ref = "benmanesversion" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
